# Generated by Django 2.0.4 on 2018-06-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20180603_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Visitor'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Visitor'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Visitor'),
        ),
    ]
