# Generated by Django 2.0.4 on 2018-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20180607_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('short_description', models.CharField(max_length=1000)),
                ('image_loaction', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Type',
            field=models.CharField(default='Food', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
