# Generated by Django 2.0.4 on 2018-05-19 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camping_number', models.IntegerField()),
                ('free_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds_taken', models.IntegerField()),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camping.Camping')),
            ],
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_time', models.DateTimeField()),
                ('returned_time', models.DateTimeField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camping.Spot'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camping.Tent'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
