# Generated by Django 2.0.4 on 2018-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tent',
            name='returned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tent',
            name='taken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
