# Generated by Django 2.0.4 on 2018-05-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_auto_20180521_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Visitor'),
        ),
    ]
