# Generated by Django 2.0.4 on 2018-05-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryticket',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryticket',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
