# Generated by Django 2.0.4 on 2018-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180604_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checked_in',
            field=models.NullBooleanField(),
        ),
    ]
